(function(g){var window=this;var BEa=function(a,b){return g.Zb(a,b)},c6=function(a){g.Rn(a,"zx",g.zc());
return a},d6=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.Un(a.o,b,c)},CEa=function(a,b){var c=[];
g.Dl(b,function(a){try{var b=g.tE.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.sE(b)&&c.push(a):c.push(a)},a);
return c},DEa=function(a,b){var c=CEa(a,b);
(0,g.C)(c,function(a){g.tE.prototype.remove.call(this,a)},a)},EEa=function(a){if(a.Ld){if(a.Ld.locationOverrideToken)return{locationOverrideToken:a.Ld.locationOverrideToken};
if(null!=a.Ld.latitudeE7&&null!=a.Ld.longitudeE7)return{latitudeE7:a.Ld.latitudeE7,longitudeE7:a.Ld.longitudeE7}}return null},FEa=function(a,b,c,d){var e=new g.In(null,void 0);
a&&g.Jn(e,a);b&&g.Kn(e,b);c&&g.Ln(e,c);d&&g.Mn(e,d);return e},e6=function(a,b){g.mF[a]=!0;
var c=g.kF();c&&c.publish.apply(c,arguments);g.mF[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.C=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Cn;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",GEa(this,a.capabilities||""),HEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},GEa=function(a,b){a.capabilities.clear();
(0,g.re)(b.split(","),g.Na(BEa,IEa)).forEach(function(b){a.capabilities.add(b)})},HEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},JEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},KEa=function(a){return new g6(a)},LEa=function(a){return g.Fa(a)?(0,g.I)(a,KEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Fa(a)?"["+(0,g.I)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},MEa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.Ua(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.Ua(a,function(a){return h6(a,b)})},NEa=function(){var a=(0,g.zI)();
a&&DEa(a,a.o.be(!0))},n6=function(){var a=g.CI("yt-remote-connected-devices")||[];
g.ub(a);return a},OEa=function(a){if(g.Za(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},PEa=function(a){g.BI("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.CI("yt-remote-device-id");a||(a=k6(),g.BI("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.Ya(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.Ya(a,b);g.EI()&&g.wb(a,b);a=OEa(a);if(g.Za(a))try{g.aI("remote_sid")}catch(c){}else try{g.$H("remote_sid",a.join(","),-1)}catch(c){}},QEa=function(){return g.CI("yt-remote-session-browser-channel")},REa=function(){return g.CI("yt-remote-local-screens")||[]},SEa=function(){g.BI("yt-remote-lounge-token-expiration",!0,86400)},TEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(REa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.wj)(c,function(a){return!g.Ya(b,a)})&&SEa();
g.BI("yt-remote-local-screens",a,31536E3)},UEa=function(a,b){g.BI("yt-remote-session-browser-channel",a);
g.BI("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.Ya(c,d)||c.push(d);PEa(c);q6()},r6=function(a){a||(g.DI("yt-remote-session-screen-id"),g.DI("yt-remote-session-video-id"));
q6();a=n6();g.db(a,p6());PEa(a)},VEa=function(){if(!s6){var a=g.EE();
a&&(s6=new g.nE(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},WEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?XEa(a.shift(),function(){u6(a)}):v6()},YEa=function(a){return"chrome-extension://"+a+w6},XEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=WEa();
a&&a(!1,"No cast extension found")},$Ea=function(){if(ZEa){var a=2,b=WEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;XEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},aFa=function(){$Ea();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.z)(a,c):a;this.Fd=b;this.D=(0,g.z)(this.aL,this);this.o=!1;this.A=0;this.C=this.Ea=null;this.B=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.C=b;this.G=c;this.F=d||1;this.B=45E3;this.Z=new g.Yn(this);this.A=new g.Ug;this.A.setInterval(250)},cFa=function(a,b,c){a.dk=1;
a.yh=c6(b.clone());a.jj=c;a.D=!0;bFa(a,null)},A6=function(a,b,c,d,e){a.dk=1;
a.yh=c6(b.clone());a.jj=null;a.D=c;e&&(a.JF=!1);bFa(a,d)},bFa=function(a,b){a.Xk=(0,g.H)();
B6(a);a.Zh=a.yh.clone();d6(a.Zh,"t",a.F);a.bo=0;a.Sc=a.o.Rt(a.o.Tn()?b:null);0<a.zu&&(a.gr=new g.lm((0,g.z)(a.TG,a,a.Sc),a.zu));a.Z.X(a.Sc,"readystatechange",a.eV);var c=a.Hi?g.jc(a.Hi):{};a.jj?(a.ds="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Sc.send(a.Zh,a.ds,a.jj,c)):(a.ds="GET",a.JF&&!g.fe&&(c.Connection="close"),a.Sc.send(a.Zh,a.ds,null,c));a.o.yf(1)},fFa=function(a,b,c){for(var d=!0;!a.oi&&a.bo<c.length;){var e=dFa(a,c);
if(e==C6){4==b&&(a.zh=4,D6(15),d=!1);break}else if(e==eFa){a.zh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.zh=1,D6(17),d=!1);a.Ef=a.Ef&&d;d||(F6(a),G6(a))},dFa=function(a,b){var c=a.bo,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return eFa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.bo=d+c;return e},hFa=function(a,b){a.Xk=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.Zh=a.yh.clone();g.Rn(a.Zh,"DOMAIN",c);g.Rn(a.Zh,"t",a.F);try{a.Gf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.zh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in gFa)k=H6[l]=gFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Hd(g.Vc("b/12014412"),d+"</body></html>");a.Gf.open();a.Gf.write(g.vd(c));a.Gf.close();a.Gf.parentWindow.m=(0,g.z)(a.lU,a);a.Gf.parentWindow.d=(0,g.z)(a.WE,a,!0);a.Gf.parentWindow.rpcClose=(0,g.z)(a.WE,a,!1);c=a.Gf.createElement("DIV");a.Gf.parentWindow.document.body.appendChild(c);d=g.id(a.Zh.toString());d=g.uc(g.fd(d));d=g.Hd(g.Vc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Dd(c,g.vd(d));a.o.yf(1)},B6=function(a){a.uy=(0,g.H)()+
a.B;
iFa(a,a.B)},iFa=function(a,b){if(null!=a.Bl)throw Error("WatchDog timer not null");
a.Bl=I6((0,g.z)(a.AU,a),b)},J6=function(a){a.Bl&&(g.w.clearTimeout(a.Bl),a.Bl=null)},G6=function(a){a.o.JB()||a.oi||a.o.Mq(a)},F6=function(a){J6(a);
g.Gf(a.gr);a.gr=null;a.A.stop();g.eo(a.Z);if(a.Sc){var b=a.Sc;a.Sc=null;b.abort();b.dispose()}a.Gf&&(a.Gf=null)},E6=function(a,b){try{a.o.PE(a,b),a.o.yf(4)}catch(c){}},kFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;jFa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){kFa(a,b,c,d,f)},f)})}},jFa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},lFa=function(a){this.o=a;
this.A=new y6},mFa=function(a){var b=L6(a.o,a.Ql,"/mail/images/cleardot.gif");
c6(b);kFa(b.toString(),5E3,(0,g.z)(a.bK,a),3,2E3);a.yf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.me=new z6(a,void 0,void 0,void 0),a.me.Hi=a.xu,b=a.o,b=L6(b,b.Tn()?a.Jm:null,a.yu),D6(5),!g.de||g.Nc(10))d6(b,"TYPE","xmlhttp"),A6(a.me,b,!1,a.Jm,!1);else{d6(b,"TYPE","html");var c=a.me;a=!!a.Jm;c.dk=3;c.yh=c6(b.clone());hFa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.B=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},nFa=function(a,b){this.o=a;
this.map=b;this.context=null},oFa=function(a){g.If.call(this,"statevent",a)},pFa=function(a,b){g.If.call(this,"timingevent",a);
this.size=b},qFa=function(a){g.If.call(this,"serverreachability",a)},tFa=function(a){rFa(a);
if(3==a.o){var b=a.An++,c=a.pp.clone();g.Rn(c,"SID",a.C);g.Rn(c,"RID",b);g.Rn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.C,b,void 0);b.dk=2;b.yh=c6(c.clone());(new Image).src=b.yh;b.Xk=(0,g.H)();B6(b)}sFa(a)},uFa=function(a){a.yK(1,0);
a.pp=L6(a,null,a.wu);Q6(a)},rFa=function(a){a.nh&&(a.nh.abort(),a.nh=null);
a.zc&&(a.zc.cancel(),a.zc=null);a.Bg&&(g.w.clearTimeout(a.Bg),a.Bg=null);R6(a);a.ge&&(a.ge.cancel(),a.ge=null);a.sh&&(g.w.clearTimeout(a.sh),a.sh=null)},vFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new nFa(a.VP++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.ge||a.sh||(a.sh=I6((0,g.z)(a.VE,a),0),a.Uj=0)},xFa=function(a,b){if(1==a.o){if(!b){a.An=Math.floor(1E5*Math.random());
var c=a.An++,d=new z6(a,"",c,void 0);d.Hi=null;var e=S6(a),f=a.pp.clone();g.Rn(f,"RID",c);g.Rn(f,"CVER","1");P6(a,f);cFa(d,f,e);a.ge=d;a.o=2}}else 3==a.o&&(b?wFa(a,b):0==a.A.length||a.ge||wFa(a))},wFa=function(a,b){if(b)if(6<a.si){a.A=a.B.concat(a.A);
a.B.length=0;var c=a.An-1;var d=S6(a)}else c=b.G,d=b.jj;else c=a.An++,d=S6(a);var e=a.pp.clone();g.Rn(e,"SID",a.C);g.Rn(e,"RID",c);g.Rn(e,"AID",a.xk);P6(a,e);c=new z6(a,a.C,c,a.Uj+1);c.Hi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ge=c;cFa(c,e,d)},P6=function(a,b){if(a.Ed){var c=a.Ed.pB();
c&&g.Nb(c,function(a,c){g.Rn(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.si&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.si?e:f-d;try{g.Nb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.A.splice(0,b));
return c.join("&")},yFa=function(a){a.zc||a.Bg||(a.G=1,a.Bg=I6((0,g.z)(a.UE,a),0),a.Kj=0)},T6=function(a){if(a.zc||a.Bg||3<=a.Kj)return!1;
a.G++;a.Bg=I6((0,g.z)(a.UE,a),zFa(a,a.Kj));a.Kj++;return!0},M6=function(a,b,c){a.Xr=c;
a.Sf=b.Og;a.F||uFa(a)},R6=function(a){null!=a.wi&&(g.w.clearTimeout(a.wi),a.wi=null)},zFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Ed&&(c=null);var d=(0,g.z)(a.WV,a);c||(c=new g.In("//www.google.com/images/cleardot.gif"),c6(c));jFa(c.toString(),1E4,d)}else D6(2);AFa(a,b)},AFa=function(a,b){a.o=0;
a.Ed&&a.Ed.nA(b);sFa(a);rFa(a)},sFa=function(a){a.o=0;
a.Sf=-1;if(a.Ed)if(0==a.B.length&&0==a.A.length)a.Ed.Dt();else{g.jb(a.B);var b=g.jb(a.A);a.B.length=0;a.A.length=0;a.Ed.Dt(b)}},L6=function(a,b,c){var d=g.Sn(c);
if(""!=d.A)b&&g.Kn(d,b+"."+d.A),g.Ln(d,d.D);else{var e=window.location;d=FEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.km&&g.Nb(a.km,function(a,b){g.Rn(d,b,a)});
g.Rn(d,"VER",a.si);P6(a,d);return d},I6=function(a,b){if(!g.Ia(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new oFa(V6,a))},BFa=function(){},CFa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.J.call(this);
this.o=new g.V(this.bU,0,this);g.K(this,this.o);this.Fd=5E3;this.A=0;if(g.Ia(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ia(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},X6=function(a,b,c){this.K=a;
this.F=b;this.C=new g.mE;this.A=new W6(this.zW,this);this.o=this.kb=null;this.Bb=!1;this.D=null;this.J="";this.H=this.B=0;this.G=[];this.L=c||!1},DFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Xr,sessionId:a.o.C,arrayId:a.o.xk}},EFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&xFa(a.o),tFa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},FFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.ih(a)||"";b&&(this.port=":"+b);this.domain=g.hh(a)||"";a=g.Lb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Kb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.za(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.rh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Na(a.B,d,!0),onError:g.Na(a.C,e),Id:g.Na(a.D,e)};c&&(a.Rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.VF(b,a)},JFa=function(){var a=GFa;
HFa();b7.push(a);IFa(b7)},c7=function(a,b){HFa();
var c=b7,d=KFa(a,String(b));g.Za(c)?LFa(d):(IFa(c),(0,g.C)(c,function(a){a(d)}))},HFa=function(){b7||(b7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",b7,void 0))},LFa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},IFa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},KFa=function(a,b){var c=((0,g.H)()-MFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.nH.call(this);
this.G=a;this.o=[]},NFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},OFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.re)(a.o,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=NFa(a,b[d])||c;return c},PFa=function(a,b){var c=a.o.length;
a.o=(0,g.re)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.nH.call(this);
this.F=a;this.D=b;this.C=c;this.B=d;this.A=0;this.o=null;this.Ea=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.C=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},QFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=$6(a.C,"/pairing/get_lounge_token_batch");
a7(a.C,c,{screen_ids:b.join(",")},(0,g.z)(a.oL,a),(0,g.z)(a.nL,a))}},i7=function(a){var b=LEa(REa());
b=(0,g.re)(b,function(a){return!a.uuid});
return OFa(a,b)},k7=function(a,b){TEa((0,g.I)(a.o,JEa));
b&&SEa()},m7=function(a,b){g.nH.call(this);
this.F=b;var c=g.CI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ya(c,l)}this.o=d;this.D=a;this.C=this.B=NaN;this.A=null;l7("Initialized with "+g.$g(this.o))},RFa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Tb(b)!=g.Tb(a.o))var c=!1;
else{c=g.Wb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.$g(a.o)),a.o=b,a.U("screenChange"));SFa(a)},o7=function(a){isNaN(a.C)||g.jF(a.C);
a.C=g.hF((0,g.z)(a.ix,a),0<a.B&&a.B<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},TFa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.qc("Requesting availability of screen w/o lounge token.")});
return b},SFa=function(a){a=g.Wb(g.Ob(a.o,function(a){return a}));
g.ub(a);a.length?g.BI("yt-remote-online-screen-ids",a.join(","),60):g.DI("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.C=null;this.B=[];this.D={};UFa(this)},WFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.xe();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);RFa(a.A,l,function(a){e(a?l:null)})}else c?VFa(a,c,(0,g.z)(function(a){var f=q7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));RFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},XFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},VFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.VF($6(a.F,"/pairing/get_lounge_token_batch"),e)},YFa=function(a){a.o=a.C.xe();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},UFa=function(a){r7(a);
a.C=new j7(a.F);a.C.subscribe("screenChange",(0,g.z)(a.BL,a));YFa(a);a.B=LEa(g.CI("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.B));a.A=new m7(a.F,(0,g.z)(a.xe,a,!0));a.A.subscribe("screenChange",(0,g.z)(function(){this.U("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.BI("yt-remote-automatic-screen-cache",(0,g.I)(a.B,JEa)));r7(a);a.D[b.uuid]=b.id;g.BI("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.CI("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.nH.call(this);
this.M=c;this.J=a;this.A=b;this.C=null},t7=function(a,b){c7(a.M,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.B=0;this.F=(0,g.z)(this.GW,this);this.D=(0,g.z)(this.MU,this);this.B=g.hF((0,g.z)(function(){ZFa(this,null)},this),12E4)},$Fa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.$g(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.$g(b))},ZFa=function(a,b){g.jF(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.C||a.C.id!=b){var c=(0,g.z)(a.Nq,a),d=(0,g.z)(a.Ce,a);a.AB(b,c,d,5)}}else a.Ce(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.B=this.H=null;this.K="";this.V=c;this.D=null;this.G=g.y;this.F=NaN;this.L=(0,g.z)(this.JW,this);this.o=g.y},aGa=function(a){a.o=a.J.XG(a.K,a.A.label,a.A.friendlyName,(0,g.z)(function(a){this.o=g.y;
this.Nq(a)},a),(0,g.z)(function(a){this.o=g.y;
this.Ce(a)},a))},bGa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.V;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}VEa()&&(b.env_useStageMdx=1);return g.ph(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.hF((0,g.z)(this.zk,this,null),150)},x7=function(a,b,c,d){g.nH.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.C=[];this.B=(0,g.z)(this.hT,this)},cGa=function(a,b){return b?g.Ua(a.C,function(a){return h6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},GFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.C.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.Gf(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.z)(a.SE,a,b)),b.C?a.U("yt-remote-cast2-session-change",b.C):c&&a.o.zk(null)):a.U("yt-remote-cast2-session-change",null))},dGa=function(a){var b=a.A.WG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=cGa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},jGa=function(a,b,c,d,e,f,k){eGa()?fGa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?gGa(a,c):(window.__onGCastApiAvailable=function(b,d){b?gGa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.DI("yt-remote-cast-available"),g.DI("yt-remote-cast-receiver"),hGa(),c(!1))},d?g.uF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?aFa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():($Ea(),u6(iGa.map(YEa))))):B7("Cannot initialize because not running Chrome")},hGa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);kGa(!1);g.pF(G7);G7.length=0},H7=function(){return!!g.CI("yt-remote-cast-installed")},lGa=function(){var a=g.CI("yt-remote-cast-receiver");
return a?a.friendlyName:null},mGa=function(){B7("clearCurrentReceiver");
g.DI("yt-remote-cast-receiver")},nGa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.oF("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},eGa=function(){var a=0<=g.Lb.search(/ (CrMo|Chrome|CriOS)\//);
return g.$L||a},oGa=function(a,b){F7().init(a,b)},fGa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.BI("yt-remote-cast-available",a);e6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.BI("yt-remote-cast-receiver",a);e6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.BI("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+i6(a));
a||g.DI("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},gGa=function(a,b){E7(!0);
C7(!1);oGa(a,function(a){a?(kGa(!0),g.rF("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.DI("yt-remote-cast-available"),g.DI("yt-remote-cast-receiver"),hGa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.BI("yt-remote-cast-installed",a)},I7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},kGa=function(a){B7("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Wf=!1;this.J=this.H=this.A=this.B=0;this.C=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Wf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.B=0;a.A=0;a.H=0;a.J=0;a.C=NaN;a.D=!1},N7=function(a){return a.sb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.kc(a.o);b.hasPrevious=a.Wf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.C;return b},T7=function(a,b){g.nH.call(this);
this.o=0;this.B=a;this.F=[];this.D=new g.DD;this.C=this.A=null;this.J=(0,g.z)(this.HQ,this);this.G=(0,g.z)(this.Dn,this);this.H=(0,g.z)(this.GQ,this);this.K=(0,g.z)(this.TQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Dy,this),pGa(this))):c=3;0!=c&&(b?this.Dy(c):g.hF((0,g.z)(function(){this.Dy(c)},this),0));
var d=nGa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.B.getPlayerContextData())},pGa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.B.subscribe(a,g.Na(this.dT,a),this))},a)},qGa=function(a){(0,g.C)(a.F,function(a){this.B.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Hc()&&g.FD(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.B.sendMessage(b,c)},W7=function(a,b){qGa(a);
a.B.setPlayerContextData(R7(b));pGa(a)},S7=function(a,b){a.C&&(a.C.removeUpdateListener(a.J),a.C.removeMediaListener(a.G),a.Dn(null));
a.C=b;a.C&&(c7("CP","Setting cast session: "+a.C.sessionId),a.C.addUpdateListener(a.J),a.C.addMediaListener(a.G),a.C.media.length&&a.Dn(a.C.media[0]))},rGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.z)(function(a){this.qc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.qc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.nH.call(this);
this.D=NaN;this.V=!1;this.K=this.J=this.L=this.M=NaN;this.O=[];this.B=this.G=this.C=this.ob=this.o=null;this.sa=a;this.O.push(g.XG(window,"beforeunload",(0,g.z)(this.eL,this)));this.A=[];this.ob=new L7;this.aa=b.id;this.o=sGa(this,c);this.o.subscribe("handlerOpened",this.LQ,this);this.o.subscribe("handlerClosed",this.IQ,this);this.o.subscribe("handlerError",this.JQ,this);this.o.subscribe("handlerMessage",this.KQ,this);FFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.ob.videoId;
g.EI()&&g.BI("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},sGa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.U("proxyStateChange",b)},tGa=function(a){a.D=g.hF((0,g.z)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.jF(a.D);
a.D=NaN},d8=function(a){g.jF(a.M);
a.M=NaN},uGa=function(a){e8(a);
a.L=g.hF((0,g.z)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.jF(a.L);
a.L=NaN},wGa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Y()&&a.ob.reset(),b8(a,1),f8(a,"getNowPlaying"),vGa(a)):a.F(1)},xGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ob.videoId&&(g.ec(b.params)?a.ob.o=null:a.ob.o=b.params,a.U("remotePlayerChange"))},yGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ob.listId=b.params.listId||a.ob.listId;Q7(a.ob,c,d);a.U("remoteQueueChange")},AGa=function(a,b){b.params=b.params||{};
yGa(a,b);zGa(a,b);a.U("autoplayDismissed")},zGa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.ob,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ob.playerState&&(c=-1E3);a.ob.playerState=c;c=Number(b.params.loadedTime);a.ob.J=isNaN(c)?0:c;c=Number(b.params.duration);a.ob.H=isNaN(c)?0:c;c=a.ob;var d=Number(b.params.liveIngestionTime);c.C=d;c.D=isNaN(d)?!1:!0;c=a.ob;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.ob.playerState?uGa(a):e8(a);a.U("remotePlayerChange")},BGa=function(a,b){if(-1E3!=
a.ob.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ob.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.ob,isNaN(c)?0:c);a.U("remotePlayerChange")}},CGa=function(a,b){var c="true"==b.params.muted;
a.ob.volume=parseInt(b.params.volume,10);a.ob.muted=c;a.U("remotePlayerChange")},DGa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",parseInt(b.params.timeout,10))},EGa=function(a,b){var c="true"==b.params.hasNext;
a.ob.Wf="true"==b.params.hasPrevious;a.ob.hasNext=c;a.U("previousNextChange")},vGa=function(a){g.jF(a.K);
a.K=g.hF((0,g.z)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.$g(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.jd=a;this.A=[];this.A.push(this.jd.$_s("screenChange",(0,g.z)(this.EW,this)));this.A.push(this.jd.$_s("onlineScreenChange",(0,g.z)(this.CS,this)))},JGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ZE("MDX_CONFIG")||b;NEa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),VEa()&&(h8.o="/api/loungedev"));i8||(i8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",i8,void 0));FGa();var c=j8();if(!c){var d=new p7(h8);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);jGa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.$g(b)),m8.push(g.oF("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.oF("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.oF("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.oF("yt-remote-cast2-session-change",GGa)),m8.push(g.oF("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),mGa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.NF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.$g(a)),HGa(a),c.start(),k8()||IGa())},LGa=function(){var a=KGa();
H7()&&g.CI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},KGa=function(){var a=j8().jd.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return MEa(a)},s8=function(){var a=MGa();
!a&&H7()&&lGa()&&(a={key:"cast-selector-receiver",name:lGa()});return a},MGa=function(){var a=KGa(),b=q8();
b||(b=o8());return g.Ua(a,function(a){return b&&h6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().xe();return m6(b,a)},GGa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.x("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.x("yt.mdx.remote.currentScreenId_")},NGa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},OGa=function(){return g.x("yt.mdx.remote.connectData_")},n8=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.x("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||NGa("");g.Ca("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.EI();
if(!a)return null;var b=j8().xe();return m6(b,a)},u8=function(a,b){q8()&&q8();
NGa(a.id);var c=new $7(h8,a,p8());c.connect(b,OGa());c.subscribe("beforeDisconnect",function(a){e6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},IGa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),mGa(),l8("Skipping connecting because no session screen found."))},FGa=function(){var a=p8();
if(g.ec(a)){a=p6();var b=g.CI("yt-remote-session-name")||"",c=g.CI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},HGa=function(a){a?(g.BI("yt-remote-session-app",a.app),g.BI("yt-remote-session-name",a.name)):(g.DI("yt-remote-session-app"),g.DI("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.C=new g.kH(this);g.K(this,this.C);this.C.R(b,"onCaptionsTrackListChanged",this.VR);this.C.R(b,"captionschanged",this.FQ);this.C.R(b,"captionssettingschanged",this.mG);this.C.R(b,"videoplayerreset",this.Oq);this.C.R(b,"mdxautoplaycancel",this.aK);this.O=this.C.R(b,"onVolumeChange",this.zE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.OE,this);c.subscribe("remotePlayerChange",this.Gn,this);c.subscribe("remoteQueueChange",this.Oq,this);c.subscribe("autoplayUpNext",this.lE,
this);c.subscribe("previousNextChange",this.LE,this);c.subscribe("nowAutoplaying",this.DE,this);c.subscribe("autoplayDismissed",this.kE,this);this.suggestion=null;this.J=new g.HQ(64);this.B=new g.V(this.jG,500,this);g.K(this,this.B);this.F=new g.V(this.kG,1E3,this);g.K(this,this.F);this.L=new x6(this.gW,0,this);g.K(this,this.L);this.G={};this.M=new g.V(this.KG,1E3,this);g.K(this,this.M);this.K=new g.lm(this.BO,1E3,this);g.K(this,this.K);this.V=g.y;this.mG();this.Oq();this.Gn()},z8=function(a,b){a.D.Ge(b,
a.A.getVideoData().lengthSeconds)},PGa=function(a){z8(a,0);
a.B.stop();A8(a,new g.HQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.mc(c,b));a.o.XF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.we();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.pk,EEa(c));A8(a,new g.HQ(1))},QGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{G4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.NQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.SU(a.A,d);a.J=b;RGa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.bta()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.JV(this,250);g.K(this,this.B);this.D=a;this.R(a,"presentingplayerstatechange",this.F);SGa(this,g.OU(a))},SGa=function(a,b){if(3==a.D.getPresentingPlayerType()){var c={RECEIVER_NAME:a.D.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.wV("Error on $RECEIVER_NAME",c):b.sb()||g.X(b,4)?g.wV("Playing on $RECEIVER_NAME",c):g.wV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.$W.call(this,"Play on",0,a,b);
this.B=a;this.K={};this.R(a,"onMdxReceiversChange",this.M);this.R(a,"presentingplayerstatechange",this.M);this.M()},G8=function(a){g.lV.call(this,a);
this.A={key:k6(),name:"This computer"};this.B=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.C=this.A;this.pn=new g.HQ(64);this.J=0;this.H=-1;if(!g.$N(g.Y(this.player))){a=this.player;var b=g.wQ(a);b&&(b=b.tn())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.cV(a,b.element,4)}},RGa=function(a,b,c){a.pn=c;
a.player.U("presentingplayerstatechange",new g.RQ(c,b))},H8=function(a,b){if(b.key!=a.C.key)if(b.key==a.A.key)t8();
else{a.C=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Aa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.pk,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=EEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.$g(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().xe(),(d=m6(d,b.key))&&u8(d,1))}},gFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},TGa={},IEa={cY:"atp",K2:"ska",X1:"que",f1:"mus",G2:"sus",p_:"dsp",q2:"seq"};
f6.prototype.oh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.C=this.C;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",ZEa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),iGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.J);g.h=x6.prototype;g.h.ZK=function(a){this.B=arguments;this.o=!1;this.Ea?this.C=(0,g.H)()+this.Fd:this.Ea=g.Vg(this.D,this.Fd)};
g.h.stop=function(){this.Ea&&(g.Wg(this.Ea),this.Ea=null);this.C=null;this.o=!1;this.B=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.h.W=function(){this.stop();x6.fa.W.call(this)};
g.h.aL=function(){this.C?(this.Ea=g.Vg(this.D,this.C-(0,g.H)()),this.C=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};y6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Hi=null;g.h.Ef=!1;g.h.Bl=null;g.h.uy=null;g.h.Xk=null;g.h.dk=null;g.h.yh=null;g.h.Zh=null;g.h.jj=null;g.h.Sc=null;g.h.bo=0;g.h.Gf=null;g.h.ds=null;g.h.zh=null;g.h.Km=-1;g.h.JF=!0;g.h.oi=!1;g.h.zu=0;g.h.gr=null;var eFa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.eV=function(a){a=a.target;var b=this.gr;b&&3==g.zy(a)?b.Gm():this.TG(a)};
g.h.TG=function(a){try{if(a==this.Sc)a:{var b=g.zy(this.Sc),c=this.Sc.A,d=this.Sc.getStatus();if(g.de&&!g.Nc(10)||g.fe&&!g.Mc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Kf&&!g.Dy(this.Sc))break a;this.oi||4!=b||7==c||(8==c||0>=d?this.o.yf(3):this.o.yf(2));J6(this);var e=this.Sc.getStatus();this.Km=e;var f=g.Dy(this.Sc);(this.Ef=200==e)?(4==b&&F6(this),this.D?(fFa(this,b,f),g.Kf&&this.Ef&&3==b&&(this.Z.X(this.A,"tick",this.ZU),this.A.start())):E6(this,f),this.Ef&&!this.oi&&(4==b?this.o.Mq(this):
(this.Ef=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.zh=3,D6(13)):(this.zh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Sc&&g.Dy(this.Sc)}finally{}};
g.h.ZU=function(){var a=g.zy(this.Sc),b=g.Dy(this.Sc);this.bo<b.length&&(J6(this),fFa(this,a,b),this.Ef&&4!=a&&B6(this))};
g.h.lU=function(a){I6((0,g.z)(this.kU,this,a),0)};
g.h.kU=function(a){this.oi||(J6(this),E6(this,a),B6(this))};
g.h.WE=function(a){I6((0,g.z)(this.jU,this,a),0)};
g.h.jU=function(a){this.oi||(F6(this),this.Ef=a,this.o.Mq(this),this.o.yf(4))};
g.h.cancel=function(){this.oi=!0;F6(this)};
g.h.AU=function(){this.Bl=null;var a=(0,g.H)();0<=a-this.uy?(2!=this.dk&&this.o.yf(3),F6(this),this.zh=2,D6(18),G6(this)):iFa(this,this.uy-a)};
g.h.getLastError=function(){return this.zh};g.h=lFa.prototype;g.h.xu=null;g.h.me=null;g.h.ir=!1;g.h.KB=null;g.h.mp=null;g.h.Cv=null;g.h.yu=null;g.h.Ve=null;g.h.Og=-1;g.h.Jm=null;g.h.Ql=null;g.h.connect=function(a){this.yu=a;a=L6(this.o,null,this.yu);D6(3);this.KB=(0,g.H)();var b=this.o.H;null!=b?(this.Jm=b[0],(this.Ql=b[1])?(this.Ve=1,mFa(this)):(this.Ve=2,N6(this))):(d6(a,"MODE","init"),this.me=new z6(this,void 0,void 0,void 0),this.me.Hi=this.xu,A6(this.me,a,!1,null,!0),this.Ve=0)};
g.h.bK=function(a){if(a)this.Ve=2,N6(this);else{D6(4);var b=this.o;b.Sf=b.nh.Og;U6(b,9)}a&&this.yf(2)};
g.h.Rt=function(a){return this.o.Rt(a)};
g.h.abort=function(){this.me&&(this.me.cancel(),this.me=null);this.Og=-1};
g.h.JB=function(){return!1};
g.h.PE=function(a,b){this.Og=a.Km;if(0==this.Ve)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Sf=this.Og;U6(c,2);return}this.Jm=c[0];this.Ql=c[1]}else c=this.o,c.Sf=this.Og,U6(c,2);else if(2==this.Ve)if(this.ir)D6(7),this.Cv=(0,g.H)();else if("11111"==b){if(D6(6),this.ir=!0,this.mp=(0,g.H)(),c=this.mp-this.KB,!g.de||g.Nc(10)||500>c)this.Og=200,this.me.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.mp=this.Cv=(0,g.H)(),this.ir=!1};
g.h.Mq=function(){this.Og=this.me.Km;if(this.me.Ef)0==this.Ve?this.Ql?(this.Ve=1,mFa(this)):(this.Ve=2,N6(this)):2==this.Ve&&((!g.de||g.Nc(10)?!this.ir:200>this.Cv-this.mp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Ve?D6(9):2==this.Ve&&D6(10);var a=this.o;this.me.getLastError();a.Sf=this.Og;U6(a,2)}};
g.h.Tn=function(){return this.o.Tn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.yf=function(a){this.o.yf(a)};g.h=O6.prototype;g.h.km=null;g.h.ge=null;g.h.zc=null;g.h.wu=null;g.h.pp=null;g.h.dA=null;g.h.Ep=null;g.h.An=0;g.h.VP=0;g.h.Ed=null;g.h.sh=null;g.h.Bg=null;g.h.wi=null;g.h.nh=null;g.h.Xr=null;g.h.xk=-1;g.h.BC=-1;g.h.Sf=-1;g.h.Uj=0;g.h.Kj=0;g.h.si=8;var V6=new g.jg;g.B(oFa,g.If);g.B(pFa,g.If);g.B(qFa,g.If);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.wu=b;this.km=c||{};d&&g.za(e)&&(this.km.OSID=d,this.km.OAID=e);this.F?(I6((0,g.z)(this.vA,this,a),100),uFa(this)):this.vA(a)};
g.h.vA=function(a){this.nh=new lFa(this);this.nh.xu=null;this.nh.A=this.D;this.nh.connect(a)};
g.h.JB=function(){return 0==this.o};
g.h.VE=function(a){this.sh=null;xFa(this,a)};
g.h.UE=function(){this.Bg=null;this.zc=new z6(this,this.C,"rpc",this.G);this.zc.Hi=null;this.zc.zu=0;var a=this.dA.clone();g.Rn(a,"RID","rpc");g.Rn(a,"SID",this.C);g.Rn(a,"CI",this.Xr?"0":"1");g.Rn(a,"AID",this.xk);P6(this,a);if(!g.de||g.Nc(10))g.Rn(a,"TYPE","xmlhttp"),A6(this.zc,a,!0,this.Ep,!1);else{g.Rn(a,"TYPE","html");var b=this.zc,c=!!this.Ep;b.dk=3;b.yh=c6(a.clone());hFa(b,c)}};
g.h.PE=function(a,b){if(0!=this.o&&(this.zc==a||this.ge==a))if(this.Sf=a.Km,this.ge==a&&3==this.o)if(7<this.si){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.Bg){if(this.zc)if(this.zc.Xk+3E3<this.ge.Xk)R6(this),this.zc.cancel(),this.zc=null;else break a;T6(this);D6(19)}}else this.BC=c[1],0<this.BC-this.xk&&37500>c[2]&&this.Xr&&0==this.Kj&&!this.wi&&(this.wi=I6((0,g.z)(this.AQ,this),6E3));else U6(this,11)}else b!=TGa.fZ.o&&U6(this,11);else if(this.zc==a&&
R6(this),!g.D(b)){c=this.D.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.xk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.C=e[1],this.Ep=e[2],e=e[3],null!=e?this.si=e:this.si=6,this.o=3,this.Ed&&this.Ed.pA(),this.dA=L6(this,this.Tn()?this.Ep:null,this.wu),yFa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Ed&&this.Ed.oA(e),this.Kj=0)}}};
g.h.AQ=function(){null!=this.wi&&(this.wi=null,this.zc.cancel(),this.zc=null,T6(this),D6(20))};
g.h.Mq=function(a){if(this.zc==a){R6(this);this.zc=null;var b=2}else if(this.ge==a)this.ge=null,b=1;else return;this.Sf=a.Km;if(0!=this.o)if(a.Ef)1==b?(b=(0,g.H)()-a.Xk,V6.dispatchEvent(new pFa(V6,a.jj?a.jj.length:0,b,this.Uj)),Q6(this),this.B.length=0):yFa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Sf)){if(d=1==b)this.ge||this.sh||1==this.o||2<=this.Uj?d=!1:(this.sh=I6((0,g.z)(this.VE,this,a),zFa(this,this.Uj)),this.Uj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.yK=function(a){if(!g.Ya(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.WV=function(a){a?D6(2):(D6(1),AFa(this,8))};
g.h.Rt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.sy;a.H=!1;return a};
g.h.isActive=function(){return!!this.Ed&&this.Ed.isActive(this)};
g.h.yf=function(a){V6.dispatchEvent(new qFa(V6,a))};
g.h.Tn=function(){return!(!g.de||g.Nc(10))};
g.h=BFa.prototype;g.h.pA=function(){};
g.h.oA=function(){};
g.h.nA=function(){};
g.h.Dt=function(){};
g.h.pB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.J);g.h=W6.prototype;g.h.bU=function(){this.Fd=Math.min(3E5,2*this.Fd);this.C();this.A&&this.start()};
g.h.start=function(){var a=this.Fd+15E3*Math.random();g.rv(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Fd=5E3};g.B(X6,BFa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.h.Ck=function(a){return this.C.Ii(a)};
g.h.U=function(a,b){return this.C.U.apply(this.C,arguments)};
g.h.dispose=function(){this.Bb||(this.Bb=!0,g.Gf(this.C),EFa(this),g.Gf(this.A),this.A=null)};
g.h.la=function(){return this.Bb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.B=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Ed=null);d.Ed=this;this.o=d;e?this.o.connect(a,b,this.F,e.C,e.xk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.mc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&vFa(this.o,c)};
g.h.pA=function(){this.A.reset();this.D=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)vFa(this.o,a[b])}this.U("handlerOpened")};
g.h.nA=function(a){var b=2==a&&401==this.o.Sf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.Dt=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.pB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.D&&g.mc(a,this.D);return a};
g.h.oA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),tFa(this.o)):this.U("handlerMessage",new CFa(a[0],a[1]))};
g.h.zW=function(){this.A.isActive();var a=this.o,b=0;a.zc&&b++;a.ge&&b++;0!=b||this.connect(this.D,this.B)};Z6.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var MFa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.nH);g7.prototype.xe=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.nH);var UGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ea)&&this.VG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ea)||(g.jF(this.Ea),this.Ea=NaN)};
g.h.W=function(){this.stop();h7.fa.W.call(this)};
g.h.VG=function(){this.Ea=NaN;this.o=g.VF($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.z)(this.BW,this),onError:(0,g.z)(this.AW,this),Id:(0,g.z)(this.DW,this)})};
g.h.BW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.B;this.U("pairingComplete",new g6(c))};
g.h.AW=function(a){this.o=null;a.status&&404==a.status?this.A>=UGa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=UGa[this.A],this.Ea=g.hF((0,g.z)(this.VG,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.DW=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.U("screenChange");!g.CI("yt-remote-lounge-token-expiration")&&QFa(this);g.jF(this.A);this.A=g.hF((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);NFa(this,a);k7(this,!1);this.U("screenChange");b(a);a.token||QFa(this)};
g.h.remove=function(a,b){var c=i7(this);PFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.Tr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.W=function(){g.jF(this.A);j7.fa.W.call(this)};
g.h.oL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.nL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.nH);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.CI("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.H)()-144E5<a?0:a)?o7(this):(this.B=(0,g.H)()+3E5,g.BI("yt-remote-fast-check-period",this.B),this.ix())};
g.h.isEmpty=function(){return g.ec(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Ob(this.o,function(b,d){return b&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.jF(this.C);this.C=NaN;this.A&&(this.A.abort(),this.A=null);m7.fa.W.call(this)};
g.h.ix=function(){g.jF(this.C);this.C=NaN;this.A&&this.A.abort();var a=TFa(this);if(g.Tb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Wb(a).join(",")},(0,g.z)(this.DT,this,a),(0,g.z)(this.CT,this))}else n7(this,{}),o7(this)};
g.h.DT=function(a,b){this.A=null;var c=g.Wb(TFa(this));if(g.vb(c,g.Wb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.qc("Changing Screen set during request."),this.ix()};
g.h.CT=function(a){this.qc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.qc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.C.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.C.add(a,b,c)};
g.h.remove=function(a,b,c){this.C.remove(a,b,c);this.A.update()};
g.h.Tr=function(a,b,c,d){this.C.contains(a)?this.C.Tr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.xe=function(a){return a?this.o:g.gb(this.o,(0,g.re)(this.B,function(a){return!this.contains(a)},this))};
g.h.WG=function(){return(0,g.re)(this.xe(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.XG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Gf(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Gf(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.FW=function(a,b,c,d){g.VF($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new g6(d.screen||{});if(!e.name||XFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);XFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
Id:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Gf(this.C);g.Gf(this.A);p7.fa.W.call(this)};
g.h.BL=function(){YFa(this);this.U("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.nH);g.h=s7.prototype;g.h.Nq=function(a){this.C=a;this.U("sessionScreen",this.C)};
g.h.Ce=function(a){this.la()||(a&&t7(this,""+a),this.C=null,this.U("sessionScreen",null))};
g.h.info=function(a){c7(this.M,a)};
g.h.ZG=function(){return null};
g.h.zx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.zx("");s7.fa.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.yx=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);$Fa(this)};
g.h.zk=function(a){this.info("launchWithParams no-op for Cast: "+g.$g(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.z)(function(){this.Ce()},this),(0,g.z)(function(){this.Ce(Error("Failed to stop receiver app."))},this)):this.Ce(Error("Stopping cast device witout session."))};
g.h.zx=g.y;g.h.W=function(){this.info("disposeInternal");g.jF(this.B);this.B=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.fa.W.call(this)};
g.h.MU=function(a,b){if(!this.la())if(b){var c=g.ny(b);if(g.Ja(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.$g(c));switch(d){case "mdxSessionStatus":ZFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.AB=function(a,b,c,d){WFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.hF((0,g.z)(this.AB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.ZG=function(){return this.o};
g.h.GW=function(a){this.la()||a||(t7(this,"Cast session died."),this.Ce())};g.B(v7,s7);g.h=v7.prototype;g.h.yx=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.zk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.y;g.jF(this.F);this.B?this.B.stop((0,g.z)(this.Ce,this,null),(0,g.z)(this.Ce,this,"Failed to stop DIAL device.")):this.Ce()};
g.h.W=function(){this.o();this.o=g.y;g.jF(this.F);this.B&&this.B.removeUpdateListener(this.L);this.B=null;v7.fa.W.call(this)};
g.h.JW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.y,this.Ce())};
g.h.av=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,bGa(this));a(b);aGa(this)}else this.G=(0,g.z)(function(){g.jF(this.F);this.G=g.y;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,bGa(this));a(b);aGa(this)},this),this.F=g.hF((0,g.z)(function(){this.G()},this),100)};
g.h.NM=function(a,b,c){WFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Nq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.av(b,c)},this),(0,g.z)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.av(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.Ce()};
w7.prototype.yx=g.y;w7.prototype.zk=function(){g.jF(this.o);this.o=NaN;var a=m6(this.J.xe(),this.A.label);a?this.Nq(a):this.Ce(Error("No such screen"))};
w7.prototype.W=function(){g.jF(this.o);this.o=NaN;w7.fa.W.call(this)};g.B(x7,g.nH);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.z)(this.RE,this),(0,g.z)(this.lT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.iR,this);chrome.cast.initialize(c,(0,g.z)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.B),JFa(),this.A.subscribe("onlineScreenChange",(0,g.z)(this.YG,this)),this.C=dGa(this),chrome.cast.setCustomReceivers(this.C,g.y,(0,g.z)(function(a){this.qc("Failed to set initial custom receivers: "+g.$g(a))},this)),this.U("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.z)(function(a){this.qc("Failed to initialize API: "+g.$g(a));
b(!1)},this))};
g.h.EV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.C;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.xe(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=cGa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.y,(0,g.z)(function(a){this.qc("Failed to set initial custom receivers: "+g.$g(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.zx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.FV=function(a){this.la()?this.qc("Setting connection data on disposed cast v2"):this.o?this.o.zk(a):this.qc("Setting connection data without a session")};
g.h.IW=function(){this.la()?this.qc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.RE,this),(0,g.z)(this.HT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.z)(this.YG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],GFa);g.Gf(this.o);x7.fa.W.call(this)};
g.h.qc=function(a){c7("Controller",a)};
g.h.SE=function(a,b){this.o==a&&(b||A7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.hT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.C&&this.U("yt-remote-cast2-session-change",this.o.C);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.qc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.qc("Stopping receiver w/o session: "+a.friendlyName)}else this.qc("onReceiverAction_ called without receiver.")};
g.h.iR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.qc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.qc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.C)return y7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.C),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.qc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.NM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.z)(b.av,b))};
g.h.RE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.qc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.xe(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Gf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.z)(this.SE,this,this.o)),this.o.zk(null));this.o.yx(a)}}};
g.h.HW=function(){return this.o?this.o.ZG():null};
g.h.HT=function(a){this.la()||(this.qc("Failed to estabilish a session: "+g.$g(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.lT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.U("yt-remote-cast2-availability-change",z7(this))}};
g.h.YG=function(){this.la()||(this.C=dGa(this),y7("Updating custom receivers: "+g.$g(this.C)),chrome.cast.setCustomReceivers(this.C,g.y,(0,g.z)(function(){this.qc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.FV;x7.prototype.setConnectedScreenStatus=x7.prototype.EV;x7.prototype.stopSession=x7.prototype.IW;x7.prototype.getCastSession=x7.prototype.HW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Wf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.C=a.liveIngestionTime,this.D=!isNaN(this.C))};
g.h.sb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.nH);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.y,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.y,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.y,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.U("remotePlayerChange")}else V7(this,g.Na(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.y,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.U("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.C){if(c.volume!=a){var d=Math.round(a)/100;this.C.setReceiverVolumeLevel(d,(0,g.z)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.qc("failed to set receiver volume.")},this))}c.muted!=b&&this.C.setReceiverMuted(b,(0,g.z)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.qc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.Na(this.setVolume,a,b))};
g.h.XF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.$g(b.style),g.mc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.Na(this.XF,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ob.id});var c=U7(this);c.audioTrackId=b.Ob.id;W7(this,c)}else V7(this,g.Na(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.za(b)&&(O7(l,b),m.currentTime=b);g.za(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.$g(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Uq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.Na(this.Uq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.Na(this.nextVideo,a,b))};
g.h.PA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.PA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}T7.fa.dispose.call(this)};
g.h.W=function(){qGa(this);this.B=null;this.D.clear();S7(this,null);T7.fa.W.call(this)};
g.h.Dy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.GD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.dT=function(a,b){this.U(a,b)};
g.h.HQ=function(a){if(!a)this.Dn(null),S7(this,null);else if(this.C.receiver.volume){a=this.C.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.Dn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),rGa(this),this.U("remotePlayerChange")};
g.h.GQ=function(a){a?(rGa(this),this.U("remotePlayerChange")):this.Dn(null)};
g.h.Qx=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.TQ=function(){var a=nGa();a&&S7(this,a)};
g.h.qc=function(a){c7("CP",a)};g.B($7,g.nH);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.ob.listId=c);this.ob.videoId=d;this.ob.index=k||0;this.ob.state=3;O7(this.ob,m);this.B="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.$g(l));this.o.connect({method:"setPlaylist",
params:g.$g(l)},a,QEa())}else a8("Connecting without params"),this.o.connect({},a,QEa());tGa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),b8(this,3));$7.fa.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.jF(this.J);this.J=NaN;g.jF(this.K);this.K=NaN;this.C=null;g.YG(this.O);this.O.length=0;this.o.dispose();$7.fa.W.call(this);this.B=this.G=this.A=this.ob=this.o=null};
g.h.eL=function(){this.F(2)};
g.h.LQ=function(){a8("Channel opened");this.V&&(this.V=!1,d8(this),this.M=g.hF((0,g.z)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
UEa(DFa(this.o),this.aa)};
g.h.IQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.JQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.V=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.KQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.$g(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.ny(a.params.devices);this.A=(0,g.I)(a,function(a){return new f6(a)});
a=!!g.Ua(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
wGa(this,a);break;case "loungeScreenDisconnected":g.eb(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
wGa(this,!1);break;case "remoteConnected":var b=new f6(g.ny(a.params.device));g.Ua(this.A,function(a){return b?a.id==b.id:!1})||g.bb(this.A,b);
break;case "remoteDisconnected":b=new f6(g.ny(a.params.device));g.eb(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":yGa(this,a);break;case "nowPlaying":AGa(this,a);break;case "onStateChange":zGa(this,a);break;case "onAdStateChange":BGa(this,a);break;case "onVolumeChanged":CGa(this,a);break;case "onSubtitlesTrackChanged":xGa(this,a);break;case "nowAutoplaying":DGa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.U("autoplayModeChange",this.B);"DISABLED"==this.B&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":EGa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.mV=function(){if(this.C){var a=this.C;this.C=null;this.ob.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Ck;$7.prototype.ia=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ia;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.U("beforeDisconnect",a);1==a&&r6();EFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.ea=function(){var a=this.ob;this.C&&(a=this.ob.clone(),Q7(a,this.C,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.ea;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.ob.videoId&&(this.C=b.videoId,g.jF(this.J),this.J=g.hF((0,g.z)(this.mV,this),5E3));var c=[];this.ob.listId==b.listId&&this.ob.videoId==b.videoId&&this.ob.index==b.index||c.push("remoteQueueChange");this.ob.playerState==b.playerState&&this.ob.volume==b.volume&&this.ob.muted==b.muted&&P7(this.ob)==P7(b)&&g.$g(this.ob.o)==g.$g(b.o)||c.push("remotePlayerChange");this.ob.reset(a);(0,g.C)(c,function(a){this.U(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Y=function(){var a=this.o.F.id,b=g.Ua(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Y;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ba=function(){return this.B||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ba;$7.prototype.ga=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.ga;$7.prototype.xa=function(){if(!isNaN(this.H())){var a=this.o.A;g.tv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);vGa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.xe=function(a){return this.jd.$_gs(a)};
g.h.contains=function(a){return!!this.jd.$_c(a)};
g.h.get=function(a){return this.jd.$_g(a)};
g.h.start=function(){this.jd.$_st()};
g.h.add=function(a,b,c){this.jd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.jd.$_r(a,b,c)};
g.h.Tr=function(a,b,c,d){this.jd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.jd.$_ubk(this.A[a]);this.A.length=0;this.jd=null;g8.fa.W.call(this)};
g.h.EW=function(){this.U("screenChange")};
g.h.CS=function(){this.U("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.FW;p7.prototype.$_gsppc=p7.prototype.XG;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.Tr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.xe;p7.prototype.$_gos=p7.prototype.WG;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Ck;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.B.stop();this.F.stop();this.L.stop();this.V();this.o.unsubscribe("proxyStateChange",this.OE,this);this.o.unsubscribe("remotePlayerChange",this.Gn,this);this.o.unsubscribe("remoteQueueChange",this.Oq,this);this.o.unsubscribe("autoplayUpNext",this.lE,this);this.o.unsubscribe("previousNextChange",this.LE,this);this.o.unsubscribe("nowAutoplaying",this.DE,this);this.o.unsubscribe("autoplayDismissed",this.kE,this);this.o=this.D=null};
g.h.oD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Gm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.FQ=function(a){this.L.ZK(a)};
g.h.gW=function(a){this.oD("control_subtitles_set_track",g.ec(a)?null:a)};
g.h.mG=function(){var a=this.A.getOption("captions","track");g.ec(a)||C8(this,a)};
g.h.zE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Gn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Gn,this)}};
g.h.VR=function(){g.ec(this.G)||QGa(this,this.G);this.H=!1};
g.h.OE=function(a,b){this.F.stop();2==b&&this.kG()};
g.h.Gn=function(){if(B8(this)){this.B.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.bl(1);break;case 1082:case 1083:this.D.bl(0);break;default:this.D.bl(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.HQ(8));this.jG();break;case 1085:case 3:A8(this,new g.HQ(9));break;case 1083:case 0:A8(this,new g.HQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.HQ(4));break;case 2:A8(this,new g.HQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.HQ(64));break;case -1E3:A8(this,new g.HQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.G=a,QGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.KG()}else PGa(this)};
g.h.LE=function(){this.A.U("mdxpreviousnextchange")};
g.h.Oq=function(){B8(this)||PGa(this)};
g.h.aK=function(){this.o.PA()};
g.h.lE=function(a){a&&(a=g.VF("/watch_queue_ajax",{method:"GET",bd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.nU,this)}))&&(this.V=(0,g.z)(a.abort,a))};
g.h.nU=function(a,b){var c=new g.AP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.DE=function(a){isNaN(a)||this.A.U("mdxnowautoplaying",a)};
g.h.kE=function(){this.A.U("mdxautoplaycanceled")};
g.h.BO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.KG=function(){if(B8(this)){var a=U7(this.o);this.C.Ka(this.O);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.O=this.C.R(this.A,"onVolumeChange",this.zE)}};
g.h.jG=function(){this.B.stop();if(!this.o.la()){var a=U7(this.o);a.sb()&&A8(this,new g.HQ(8));z8(this,P7(a));this.B.start()}};
g.h.kG=function(){this.F.stop();this.B.stop();var a=this.o.B.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.F=function(a){SGa(this,a.state)};g.r(F8,g.$W);F8.prototype.M=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.K=g.xb(a,this.G,this),g.aX(this,(0,g.I)(a,this.G)),a=this.B.getOption("remote","currentReceiver"),this.xf(this.G(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.G=function(a){return a.key};
F8.prototype.wf=function(a){return"cast-selector-receiver"==a?"Cast...":this.K[a].name};
F8.prototype.ld=function(a){g.$W.prototype.ld.call(this,a);this.B.setOption("remote","currentReceiver",this.K[a]);this.D.Jb()};g.r(G8,g.lV);g.h=G8.prototype;g.h.create=function(){JGa(g.SN(g.Y(this.player)));this.D.push(g.oF("yt-remote-before-disconnect",this.BQ,this));this.D.push(g.oF("yt-remote-connection-change",this.mT,this));this.D.push(g.oF("yt-remote-receiver-availability-change",this.ME,this));this.D.push(g.oF("yt-remote-auto-connect",this.kT,this));this.D.push(g.oF("yt-remote-receiver-resumed",this.jT,this));this.ME()};
g.h.load=function(){this.player.cancelPlayback();g.lV.prototype.load.call(this);this.B=new y8(this,this.player,this.o);var a=(a=OGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Ge(a);RGa(this,this.pn,this.pn);g.D0(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.C=this.A;g.Hf(this.B,this.o);this.o=this.B=null;g.lV.prototype.unload.call(this);g.D0(this.player.app,5)};
g.h.W=function(){g.pF(this.D);g.lV.prototype.W.call(this)};
g.h.Th=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.oD.apply(this.B,[a].concat(g.ea(c)))};
g.h.bl=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.TK=function(){return this.loaded?this.B.suggestion:null};
g.h.Wf=function(){return this.o?U7(this.o).Wf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Ge=function(a,b){this.J=a||0;this.player.U("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Kc():!a.isAdPlaying()&&this.player.Kc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.C+N7(a):a.C,isAtLiveHead:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.B?a.B+N7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Uq=function(){this.o&&this.o.Uq()};
g.h.BQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.mT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.C=b,this.load())}else g.Gf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.ME=function(){this.F=[this.A].concat(LGa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.kT=function(){var a=s8();H8(this,a)};
g.h.jT=function(){this.C=s8()};
g.h.Gc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.C:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.Qx=function(){this.o.Qx()};
g.h.uc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.WZ.remote=G8;})(_yt_player);
